// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectSSH() {
  return window['go']['main']['App']['ConnectSSH']();
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function StatusConnection() {
  return window['go']['main']['App']['StatusConnection']();
}
