// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ConnectSSH():Promise<main.Request>;

export function DisconnectSSH():Promise<main.Request>;

export function StatusConnection():Promise<boolean>;
